Die Kleinanzeige <b>$classified.title$</b> ist online verfügbar.
Wenn der Inhalt dieser Kleinanzeige Ihnen nicht zusagt, können Sie diese offline nehmen.

$if(notification_receiver_users)$
Diese Nachricht wurde
 den Benutzern gesendet : $notification_receiver_users$
$endif$

$if(notification_receiver_groups)$
  $if(!notification_receiver_users)$
  Diese Nachricht wurde
  $endif$
 den Gruppen gesendet : $notification_receiver_groups$
$endif$