The ad <b>$classified.title$</b> is available online.
If the content of this announcement does not suit you, you can deny it.

$if(notification_receiver_users)$
This message has been sent
 to following users : $notification_receiver_users$
$endif$

$if(notification_receiver_groups)$
  $if(!notification_receiver_users)$
  This message has been sent
  $endif$
 to following groups : $notification_receiver_groups$
$endif$