ALTER TABLE SC_Almanach_Event DROP CONSTRAINT PK_Almanach_Event;
ALTER TABLE SC_Almanach_Periodicity DROP CONSTRAINT PK_Almanach_Periodicity;
ALTER TABLE SC_Almanach_PeriodicityExcept DROP CONSTRAINT PK_Almanach_PeriodicityExcept;