<div style="font-family:Arial;font-size:11px">

Une nouvelle actualité vient d'être créée dans l'un de vos abonnements...<br/>

<b>$title$</b>
$description$

$if(notification_receiver_users)$
Ce message a été envoyé
 aux utilisateurs : $notification_receiver_users$
$endif$

$if(notification_receiver_groups)$
  $if(!notification_receiver_users)$
  Ce message a été envoyé
  $endif$
 aux groupes : $notification_receiver_groups$
$endif$
</div>