$if(albumPart)$
  This album contains no albums yet.<br/>
  To add one, use one of the following:
  <ul>
    <li>drag a folder in the drag and drop zone</li>
    <li>the operation "$albumOperation$"</li>
    <li><a href="$albumUrl$">clic here</a></li>
  </ul><br/><br/>
$endif$
This album contains no media yet.
$if(mediaPart)$<br/>
  To add one, use one of the following:
  <ul>
    <li>the drag and drop zone</li>
    <li>the operation "$mediaOperation$"</li>
    <li><a href="$mediaUrl$">clic here</a></li>
  </ul>
$endif$