$senderName$ le informa de la existencia de un documento...

Encontrará este documento adjunto a la publicación &quot;$publicationName$&quot; aquí :
$path$

$if(attachmentTitle)$
Nombre del documento: $attachmentTitle$<br/>
$endif$
$if(attachmentDesc)$
Descripción del documento: $attachmentDesc$<br/>
$endif$
Nombre del archivo: $attachmentFileName$
$if(attachmentCreationDate)$
Fecha de creación: $attachmentCreationDate$<br/>
$endif$
$if(attachmentSize)$
Tamaño: $attachmentSize$<br/>
$endif$
$if(attachmentAuthor)$
Autor: $attachmentAuthor$<br/>
$endif$
$if(attachmentMajorNumber)$
Versión del documento: $attachmentMajorNumber$.$attachmentMinorNumber$<br/>
$endif$
