$senderName$ информирует вас о существовании документа...

Вы найдете этот документ прикрепленным к публикации &quot;$publicationName$&quot; здесь :
$path$

$if(attachmentTitle)$
Имя документа: $attachmentTitle$<br/>
$endif$
$if(attachmentDesc)$
Описание документа: $attachmentDesc$<br/>
$endif$
Имя файла: $attachmentFileName$
$if(attachmentCreationDate)$
Дата создания: $attachmentCreationDate$<br/>
$endif$
$if(attachmentSize)$
Размер: $attachmentSize$<br/>
$endif$
$if(attachmentAuthor)$
Автор: $attachmentAuthor$<br/>
$endif$
$if(attachmentMajorNumber)$
Версия документа: $attachmentMajorNumber$.$attachmentMinorNumber$<br/>
$endif$
