$senderName$ повідомляє про наявність документа...

Цей документ ви знайдете у додатку до публікації &quot;$publicationName$&quot; тут:
$path$

$if(attachmentTitle)$
Назва документа: $attachmentTitle$<br/>
$endif$
$if(attachmentDesc)$
Опис документа: $attachmentDesc$<br/>
$endif$
Ім&#39;я файлу: $attachmentFileName$
$if(attachmentCreationDate)$
Дата створення: $attachmentCreationDate$<br/>
$endif$
$if(attachmentSize)$
Розмір: $attachmentSize$<br/>
$endif$
$if(attachmentAuthor)$
Автор: $attachmentAuthor$<br/>
$endif$
$if(attachmentMajorNumber)$
Версія документа: $attachmentMajorNumber$.$attachmentMinorNumber$<br/>
$endif$
