<h1 class="titreFenetre">Что такое RSS?</h1>
<p>
RSS — это формат распространения веб-контента. Это диалект XML. Его название является аббревиатурой от Really Simple Syndication.<br />
Речь идет о фидах, лентах или RSS-каналах.<br />
<br />
Это способ описания контента сайта: событий, статей, информации, журнальных записей и вообще любой страницы, на которой представлен периодически обновляемый контент. Этот формат позволяет Silverpeas автоматически отображать последние заголовки на информационном сайте и ссылаться на соответствующую информацию.<br />
</p>

<div class="inlineMessage">
<p>
<strong>Доступность информационных RSS-каналов обычно обозначается следующим значком<img border="0" src="/silverpeas/util/icons/rss.gif" alt="RSS" /></strong><br />
Наличие этих значков указывает веб-мастерам, желающим, что можно использовать ленту новостей с этого сайта.
</p>
</div>

<p>
К сожалению, не все сайты предоставляют RSS-канал.
</p>

<div class="txtlibform">Вот несколько RSS-каналов:</div>


<div class="rss_exemple">
<h3 class="txttitrecol">Новости</h3>
<ul>
<li><a target="_blank" href="http://www.monde-diplomatique.fr/recents.xml">Дипломатический мир</a></li>
<li><a target="_blank" href="http://www.liberation.fr/rss.php">Liberation.fr - Заголовки</a></li>
<li><a target="_blank" href="http://permanent.nouvelobs.com/cgi/rss/permanent_une">NouvelObs.com: главная страница</a></li>
<li><a target="_blank" href="http://www.rtl.fr/referencement/rtlinfo.asp">Информация о реальном времени</a></li>
<li><a target="_blank" href="http://rss.news.yahoo.com/rss/topstories">Яху! Новости - Главные новости</a></li>
</ul>
</div>
<div class="rss_exemple">
<h3 class="txttitrecol">Информатика</h3>
<ul>
<li><a target="_blank" href="http://www.zdnet.fr/feeds/rss/actualites/">ZDNet</a></li>
<li><a target="_blank" href="http://www.allhtml.com/news/news.xml">ALL HTML - Портал для веб-мастеров</a></li>
<li><a target="_blank" href="http://manchettes.branchez-vous.com/branchez-vous.xml">BRANCHEZ-VOUS.com - Новые технологии</a></li>
<li><a target="_blank" href="http://developpeur.journaldunet.com/jdnetdev.xml">Журнал сетевых разработчиков</a></li>
<li><a target="_blank" href="http://ntic.org/nouvelles/nouvelles_rss.php">NTIC.org</a></li>
</ul>
</div>
<div class="rss_exemple">
<h3 class="txttitrecol">Наука</h3>
<ul>
<li><a target="_blank" href="http://www.cite-sciences.fr/rss/sciences_actu_fr_20.xml">Город наук</a></li>
<li><a target="_blank" href="http://www.futura-sciences.com/services/rss/actu10.xml">Futura-Sciences.com</a></li>
<li><a target="_blank" href="http://www.cite-sciences.fr/rss/biomagazine_fr_20.xml">Новости науки: биожурнал</a></li>
<li><a target="_blank" href="http://www.cite-sciences.fr/rss/astro_fr_20.xml">Новости науки: журнал астрономии</a></li>
<li><a target="_blank" href="http://news.bbc.co.uk/rss/newsonline_world_edition/science/nature/rss091.xml">Новости Би-би-си | Наука/Природа | Мировое издание</a></li>
</ul>
</div>
<div class="rss_exemple">
<h3 class="txttitrecol">Спорт</h3>
<ul>
<li><a target="_blank" href="http://www.lequipe.fr/Xml/actu_rss.xml">Команда</a></li>
<li><a target="_blank" href="http://www.rtl.fr/referencement/rtlsport.asp">РТЛ Спорт</a></li>
<li><a target="_blank" href="http://www.microsite.reuters.com/rss/sportsNews">Рейтер</a></li>
</ul>
</div>
