<h1 class="titreFenetre">Що таке RSS?</h1>
<p>
RSS — це формат синдикації веб-вмісту. Це діалект XML. Його назва є абревіатурою від Really Simple Syndication.<br />
Ми говоримо про канали, канали або канали RSS.<br />
<br />
Це спосіб опису вмісту сайту: подій, статей, інформації, журнальних записів і, загалом, будь-якої сторінки, яка представляє періодично оновлюваний вміст. Цей формат дозволяє Silverpeas автоматично відображати останні заголовки на веб-сайті та посилатися на пов’язану інформацію.<br />
</p>

<div class="inlineMessage">
<p>
<strong>Доступність каналів інформації RSS зазвичай матеріалізується наступною піктограмою<img border="0" src="/silverpeas/util/icons/rss.gif" alt="RSS" /></strong><br />
Наявність цих піктограм вказує веб-майстрам, які бажають, що можна використовувати стрічку новин із цього сайту.
</p>
</div>

<p>
На жаль, не всі сайти надають RSS-канал.
</p>

<div class="txtlibform">Ось кілька каналів RSS:</div>


<div class="rss_exemple">
<h3 class="txttitrecol">Новини</h3>
<ul>
<li><a target="_blank" href="http://www.monde-diplomatique.fr/recents.xml">Дипломатичний світ</a></li>
<li><a target="_blank" href="http://www.liberation.fr/rss.php">Liberation.fr - Заголовки</a></li>
<li><a target="_blank" href="http://permanent.nouvelobs.com/cgi/rss/permanent_une">NouvelObs.com: головна сторінка</a></li>
<li><a target="_blank" href="http://www.rtl.fr/referencement/rtlinfo.asp">Інформація RTL</a></li>
<li><a target="_blank" href="http://rss.news.yahoo.com/rss/topstories">Yahoo! Новини - Головні новини</a></li>
</ul>
</div>
<div class="rss_exemple">
<h3 class="txttitrecol">Комп&#39;ютерна наука</h3>
<ul>
<li><a target="_blank" href="http://www.zdnet.fr/feeds/rss/actualites/">ZDNet</a></li>
<li><a target="_blank" href="http://www.allhtml.com/news/news.xml">ALL HTML - Портал для веб-майстрів</a></li>
<li><a target="_blank" href="http://manchettes.branchez-vous.com/branchez-vous.xml">BRANCHEZ-VOUS.com - Нові технології</a></li>
<li><a target="_blank" href="http://developpeur.journaldunet.com/jdnetdev.xml">Журнал мережевих розробників</a></li>
<li><a target="_blank" href="http://ntic.org/nouvelles/nouvelles_rss.php">NTIC.org</a></li>
</ul>
</div>
<div class="rss_exemple">
<h3 class="txttitrecol">Наука</h3>
<ul>
<li><a target="_blank" href="http://www.cite-sciences.fr/rss/sciences_actu_fr_20.xml">Місто наук</a></li>
<li><a target="_blank" href="http://www.futura-sciences.com/services/rss/actu10.xml">Futura-Sciences.com</a></li>
<li><a target="_blank" href="http://www.cite-sciences.fr/rss/biomagazine_fr_20.xml">Новини науки: біожурнал</a></li>
<li><a target="_blank" href="http://www.cite-sciences.fr/rss/astro_fr_20.xml">Наукові новини: астрономічний журнал</a></li>
<li><a target="_blank" href="http://news.bbc.co.uk/rss/newsonline_world_edition/science/nature/rss091.xml">BBC News | Наука/Природа | Всесвітнє видання</a></li>
</ul>
</div>
<div class="rss_exemple">
<h3 class="txttitrecol">спорт</h3>
<ul>
<li><a target="_blank" href="http://www.lequipe.fr/Xml/actu_rss.xml">Команда</a></li>
<li><a target="_blank" href="http://www.rtl.fr/referencement/rtlsport.asp">RTL Спорт</a></li>
<li><a target="_blank" href="http://www.microsite.reuters.com/rss/sportsNews">Reuters</a></li>
</ul>
</div>
