<h1 class="titreFenetre">¿Qué es RSS?</h1>
<p>
RSS es un formato de sindicación de contenido web. Es un dialecto de XML. Su nombre es un acrónimo de Really Simple Syndication.<br />
Hablamos de feeds, feeds o canales RSS.<br />
<br />
Es una forma de describir el contenido de un sitio: eventos, artículos, información, entradas de diario y, en general, cualquier página que presente contenido periódicamente actualizado. Este formato permite que Silverpeas muestre automáticamente los titulares más recientes en un sitio de contenido y enlace a información relacionada.<br />
</p>

<div class="inlineMessage">
<p>
<strong>La disponibilidad de fuentes de información RSS generalmente se materializa mediante el siguiente icono<img border="0" src="/silverpeas/util/icons/rss.gif" alt="RSS" /></strong><br />
La presencia de estos íconos indica a los webmasters que así lo deseen que es posible utilizar una fuente de noticias de este sitio.
</p>
</div>

<p>
Desafortunadamente, no todos los sitios ofrecen una fuente RSS.
</p>

<div class="txtlibform">Aquí hay algunos canales RSS:</div>


<div class="rss_exemple">
<h3 class="txttitrecol">Noticias</h3>
<ul>
<li><a target="_blank" href="http://www.monde-diplomatique.fr/recents.xml">El mundo diplomático</a></li>
<li><a target="_blank" href="http://www.liberation.fr/rss.php">Liberation.fr - Titulares</a></li>
<li><a target="_blank" href="http://permanent.nouvelobs.com/cgi/rss/permanent_une">NouvelObs.com: La portada</a></li>
<li><a target="_blank" href="http://www.rtl.fr/referencement/rtlinfo.asp">Información RTL</a></li>
<li><a target="_blank" href="http://rss.news.yahoo.com/rss/topstories">yahoo! Noticias - Noticias destacadas</a></li>
</ul>
</div>
<div class="rss_exemple">
<h3 class="txttitrecol">Ciencias de la Computación</h3>
<ul>
<li><a target="_blank" href="http://www.zdnet.fr/feeds/rss/actualites/">ZDNet</a></li>
<li><a target="_blank" href="http://www.allhtml.com/news/news.xml">ALL HTML - El Portal dedicado a los Webmasters</a></li>
<li><a target="_blank" href="http://manchettes.branchez-vous.com/branchez-vous.xml">BRANCHEZ-VOUS.com - Nuevas Tecnologías</a></li>
<li><a target="_blank" href="http://developpeur.journaldunet.com/jdnetdev.xml">Diario de los desarrolladores netos</a></li>
<li><a target="_blank" href="http://ntic.org/nouvelles/nouvelles_rss.php">NTIC.org</a></li>
</ul>
</div>
<div class="rss_exemple">
<h3 class="txttitrecol">Ciencia</h3>
<ul>
<li><a target="_blank" href="http://www.cite-sciences.fr/rss/sciences_actu_fr_20.xml">Ciudad de las Ciencias</a></li>
<li><a target="_blank" href="http://www.futura-sciences.com/services/rss/actu10.xml">Futura-Sciences.com</a></li>
<li><a target="_blank" href="http://www.cite-sciences.fr/rss/biomagazine_fr_20.xml">Noticias científicas: la revista Bio</a></li>
<li><a target="_blank" href="http://www.cite-sciences.fr/rss/astro_fr_20.xml">Science News: la revista de astronomía</a></li>
<li><a target="_blank" href="http://news.bbc.co.uk/rss/newsonline_world_edition/science/nature/rss091.xml">Noticias de la BBC | Ciencias/Naturaleza | Edición mundial</a></li>
</ul>
</div>
<div class="rss_exemple">
<h3 class="txttitrecol">Deporte</h3>
<ul>
<li><a target="_blank" href="http://www.lequipe.fr/Xml/actu_rss.xml">El equipo</a></li>
<li><a target="_blank" href="http://www.rtl.fr/referencement/rtlsport.asp">Deportes RTL</a></li>
<li><a target="_blank" href="http://www.microsite.reuters.com/rss/sportsNews">Reuters</a></li>
</ul>
</div>
