<h1 class="titreFenetre">Was ist RSS?</h1>
<p>
RSS ist ein Syndikationsformat für Web-Inhalte. Es handelt sich um einen Dialekt von XML. RSS ist eine Abkürzung für Really Simple Syndication (wirklich einfache Syndikation).<br />
 Man spricht von RSS-Wires, -Flows und -Channels.<br />
<br />
Es handelt sich um eine Art und Weise der Beschreibung des Inhalts einer Site: Ereignisse, Artikel, Informationen, Journal-Einträge und ganz allgemein jede Seite, die einen periodisch aktualisierten Inhalt enthält. Dieses Format ermöglicht es Silverpeas, automatisch die letzten auf einer Inhalt-Site erschienenen Titel anzuzeigen und eine Verbindung zur damit verbundenen Information zu erstellen.<br />
</p>

<div class="inlineMessage">
    <p>
    <strong>Die Verfügbarkeit von RSS-Informations-Flows wird in der Regel durch eines der beiden folgenden Icons verkörpert  <img border="0" src="<%=context%>/util/icons/rss.gif" alt="RSS" /></strong><br />
    Das Vorhandensein dieser Icons zeigt den Webmasters, die es wünschen, an, dass es möglich ist, einen Aktualitäten-Wire von dieser Site zu nutzen.
  </p>
</div>

<p>
Leider stellen nicht alle Sites einen RSS-Wire zur Verfügung.<br />
Bestimmte "Aggregator"-Sites bieten ebenfalls Wires an, sind jedoch nicht Produzenten der Informationen, die diese enthalten: siehe  <a target="_blank" href="http://www.newsisfree.com/">NewsIsFree</a>, <a target="_blank" href="http://www.syndic8.com/">Syndic8</a>.<br /><br />
</p>

<div class="txtlibform">Hier einige RSS-Wires:</div>


<div class="rss_exemple">
	<h3 class="txttitrecol">Aktualitäten</h3>
    <ul>
    	<li><a target="_blank" href="http://www.monde-diplomatique.fr/recents.xml">Le monde diplomatique</a></li>
        <li><a target="_blank" href="http://www.liberation.fr/rss.php">Liberation.fr - A la une</a></li>
        <li><a target="_blank" href="http://permanent.nouvelobs.com/cgi/rss/permanent_une">NouvelObs.com : La une</a></li>
        <li><a target="_blank" href="http://www.rtl.fr/referencement/rtlinfo.asp">RTL Info</a></li>
        <li><a target="_blank" href="http://rss.news.yahoo.com/rss/topstories">Yahoo! News - Top Stories</a></li>
    </ul>
</div>
<div class="rss_exemple">
	<h3 class="txttitrecol">Informatik</h3>
    <ul>
    	<li><a target="_blank" href="http://www.zdnet.fr/feeds/rss/actualites/">ZDNet</a></li>
        <li><a target="_blank" href="http://www.allhtml.com/news/news.xml">ALL HTML - Le Portail dédié aux Webmasters</a></li>
        <li><a target="_blank" href="http://manchettes.branchez-vous.com/branchez-vous.xml">BRANCHEZ-VOUS.com - Nouvelles Technologies</a></li>
        <li><a target="_blank" href="http://developpeur.journaldunet.com/jdnetdev.xml">Journal du Net Développeurs</a></li>
        <li><a target="_blank" href="http://ntic.org/nouvelles/nouvelles_rss.php">NTIC.org</a></li>
    </ul>
</div>
<div class="rss_exemple">
	<h3 class="txttitrecol">Sciences</h3>
    <ul>
    	<li><a target="_blank" href="http://www.cite-sciences.fr/rss/sciences_actu_fr_20.xml">Cité des Sciences</a></li>
        <li><a target="_blank" href="http://www.futura-sciences.com/services/rss/actu10.xml">Futura-Sciences.com</a></li>
        <li><a target="_blank" href="http://www.cite-sciences.fr/rss/biomagazine_fr_20.xml">Science Actualités : le Biomagazine</a></li>
        <li><a target="_blank" href="http://www.cite-sciences.fr/rss/astro_fr_20.xml">Science Actualités : le journal de l'astronomie</a></li>
        <li><a target="_blank" href="http://news.bbc.co.uk/rss/newsonline_world_edition/science/nature/rss091.xml">BBC News | Science/Nature | World Edition</a></li>
    </ul>
</div>
<div class="rss_exemple">
	<h3 class="txttitrecol">Sport</h3>
    <ul>
    	<li><a target="_blank" href="http://www.lequipe.fr/Xml/actu_rss.xml">L'équipe</a></li>
    	<li><a target="_blank" href="http://www.rtl.fr/referencement/rtlsport.asp">RTL Sport</a></li>
        <li><a target="_blank" href="http://www.microsite.reuters.com/rss/sportsNews">Reuters</a></li>
    </ul>
</div>