<h1 class="titreFenetre">What is RSS?</h1>
<p>
RSS is a specification for XML files to provide syndicated data from the Web. Its name is an acronym for Really Simple Syndication.<br />
We talk about RSS feeds or channels.<br />
<br />
It is typically used by news sites to provide information concerning the latest news stories, posts, etc., in such a way that links to the stories can be included on other web sites. This allows to automatically display latest informations of a Website into Silverpeas and to make a link to each information.<br />
</p>

<div class="inlineMessage">
    <p>
    <strong>Generally, the availability of an RSS feed is represented by the following icon  <img border="0" src="<%=context%>/util/icons/rss.gif" alt="RSS" /></strong><br />
    These icons tell webmasters they are able to run RSS feed from the website.
  </p>
</div>

<p>
Unfortunately, every website does not provide RSS feeds.<br />
Some "agregator" websites provide RSS feeds but are not the producer of the information: see <a target="_blank" href="http://www.newsisfree.com/">NewsIsFree</a>, <a target="_blank" href="http://www.syndic8.com/">Syndic8</a>.<br /><br />
</p>

<div class="txtlibform">Here are some examples of RSS feeds:</div>


<div class="rss_exemple">
	<h3 class="txttitrecol">News</h3>
    <ul>
    	<li><a target="_blank" href="http://www.monde-diplomatique.fr/recents.xml">Le monde diplomatique</a></li>
        <li><a target="_blank" href="http://www.liberation.fr/rss.php">Liberation.fr - A la une</a></li>
        <li><a target="_blank" href="http://permanent.nouvelobs.com/cgi/rss/permanent_une">NouvelObs.com : La une</a></li>
        <li><a target="_blank" href="http://www.rtl.fr/referencement/rtlinfo.asp">RTL Info</a></li>
        <li><a target="_blank" href="http://rss.news.yahoo.com/rss/topstories">Yahoo! News - Top Stories</a></li>
    </ul>
</div>
<div class="rss_exemple">
	<h3 class="txttitrecol">Computer Science</h3>
    <ul>
    	<li><a target="_blank" href="http://www.zdnet.fr/feeds/rss/actualites/">ZDNet</a></li>
        <li><a target="_blank" href="http://www.allhtml.com/news/news.xml">ALL HTML - Le Portail dédié aux Webmasters</a></li>
        <li><a target="_blank" href="http://manchettes.branchez-vous.com/branchez-vous.xml">BRANCHEZ-VOUS.com - Nouvelles Technologies</a></li>
        <li><a target="_blank" href="http://developpeur.journaldunet.com/jdnetdev.xml">Journal du Net Développeurs</a></li>
        <li><a target="_blank" href="http://ntic.org/nouvelles/nouvelles_rss.php">NTIC.org</a></li>
    </ul>
</div>
<div class="rss_exemple">
	<h3 class="txttitrecol">Sciences</h3>
    <ul>
    	<li><a target="_blank" href="http://www.cite-sciences.fr/rss/sciences_actu_fr_20.xml">Cité des Sciences</a></li>
        <li><a target="_blank" href="http://www.futura-sciences.com/services/rss/actu10.xml">Futura-Sciences.com</a></li>
        <li><a target="_blank" href="http://www.cite-sciences.fr/rss/biomagazine_fr_20.xml">Science Actualités : le Biomagazine</a></li>
        <li><a target="_blank" href="http://www.cite-sciences.fr/rss/astro_fr_20.xml">Science Actualités : le journal de l'astronomie</a></li>
        <li><a target="_blank" href="http://news.bbc.co.uk/rss/newsonline_world_edition/science/nature/rss091.xml">BBC News | Science/Nature | World Edition</a></li>
    </ul>
</div>
<div class="rss_exemple">
	<h3 class="txttitrecol">Sport</h3>
    <ul>
    	<li><a target="_blank" href="http://www.lequipe.fr/Xml/actu_rss.xml">L'équipe</a></li>
    	<li><a target="_blank" href="http://www.rtl.fr/referencement/rtlsport.asp">RTL Sport</a></li>
        <li><a target="_blank" href="http://www.microsite.reuters.com/rss/sportsNews">Reuters</a></li>
    </ul>
</div>