<h1 class="titreFenetre">Qu'est-ce que RSS ?</h1>
<p>
RSS est un format de syndication de contenu Web. C'est un dialecte de XML. Son nom est un acronyme pour Really Simple Syndication (syndication vraiment simple).<br />
On parle de fils, de flux ou de channels RSS.<br />
<br />
C'est une manière de décrire le contenu d'un site : événements, articles, informations, entrées de journal, et plus généralement toute page qui présente un contenu mis à jour de manière périodique. Ce format permet à Silverpeas d'afficher automatiquement les derniers titres parus sur un site de contenu, et de faire un lien vers l'information associée.<br />
</p>

<div class="inlineMessage">
    <p>
    <strong>La disponibilité de flux d'informations RSS est généralement matérialisée par l'icone suivante <img border="0" src="<%=context%>/util/icons/rss.gif" alt="RSS" /></strong><br />
    La présence de ces icones indique aux webmasters qui le désirent qu'il est possible d'exploiter un fil d'actualités en provenance de ce site.
  </p>
</div>

<p>
Malheureusement, tous les sites ne mettent pas à disposition un fil RSS.<br />
Certains sites "agrégateurs" proposent ausi des fils mais ne sont pas producteurs des informations qu'ils contiennent : voir <a target="_blank" href="http://www.newsisfree.com/">NewsIsFree</a>, <a target="_blank" href="http://www.syndic8.com/">Syndic8</a>.<br /><br />
</p>

<div class="txtlibform">Voici quelques fils RSS :</div>


<div class="rss_exemple">
	<h3 class="txttitrecol">Actualités</h3>
    <ul>
    	<li><a target="_blank" href="http://www.monde-diplomatique.fr/recents.xml">Le monde diplomatique</a></li>
        <li><a target="_blank" href="http://www.liberation.fr/rss.php">Liberation.fr - A la une</a></li>
        <li><a target="_blank" href="http://permanent.nouvelobs.com/cgi/rss/permanent_une">NouvelObs.com : La une</a></li>
        <li><a target="_blank" href="http://www.rtl.fr/referencement/rtlinfo.asp">RTL Info</a></li>
        <li><a target="_blank" href="http://rss.news.yahoo.com/rss/topstories">Yahoo! News - Top Stories</a></li>
    </ul>
</div>
<div class="rss_exemple">
	<h3 class="txttitrecol">Informatique</h3>
    <ul>
    	<li><a target="_blank" href="http://www.zdnet.fr/feeds/rss/actualites/">ZDNet</a></li>
        <li><a target="_blank" href="http://www.allhtml.com/news/news.xml">ALL HTML - Le Portail dédié aux Webmasters</a></li>
        <li><a target="_blank" href="http://manchettes.branchez-vous.com/branchez-vous.xml">BRANCHEZ-VOUS.com - Nouvelles Technologies</a></li>
        <li><a target="_blank" href="http://developpeur.journaldunet.com/jdnetdev.xml">Journal du Net Développeurs</a></li>
        <li><a target="_blank" href="http://ntic.org/nouvelles/nouvelles_rss.php">NTIC.org</a></li>
    </ul>
</div>
<div class="rss_exemple">
	<h3 class="txttitrecol">Sciences</h3>
    <ul>
    	<li><a target="_blank" href="http://www.cite-sciences.fr/rss/sciences_actu_fr_20.xml">Cité des Sciences</a></li>
        <li><a target="_blank" href="http://www.futura-sciences.com/services/rss/actu10.xml">Futura-Sciences.com</a></li>
        <li><a target="_blank" href="http://www.cite-sciences.fr/rss/biomagazine_fr_20.xml">Science Actualités : le Biomagazine</a></li>
        <li><a target="_blank" href="http://www.cite-sciences.fr/rss/astro_fr_20.xml">Science Actualités : le journal de l'astronomie</a></li>
        <li><a target="_blank" href="http://news.bbc.co.uk/rss/newsonline_world_edition/science/nature/rss091.xml">BBC News | Science/Nature | World Edition</a></li>
    </ul>
</div>
<div class="rss_exemple">
	<h3 class="txttitrecol">Sport</h3>
    <ul>
    	<li><a target="_blank" href="http://www.lequipe.fr/Xml/actu_rss.xml">L'équipe</a></li>
    	<li><a target="_blank" href="http://www.rtl.fr/referencement/rtlsport.asp">RTL Sport</a></li>
        <li><a target="_blank" href="http://www.microsite.reuters.com/rss/sportsNews">Reuters</a></li>
    </ul>
</div>