ALTER TABLE sc_mailinglist_message
ADD CONSTRAINT pk_mailinglist_message
PRIMARY KEY (id);
ALTER TABLE sc_mailinglist_list
ADD CONSTRAINT pk_mailinglist_list
PRIMARY KEY (id);
ALTER TABLE sc_mailinglist_external_user
ADD CONSTRAINT pk_mailinglist_external_user
PRIMARY KEY (id);
ALTER TABLE sc_mailinglist_attachment
ADD CONSTRAINT pk_mailinglist_attachment
PRIMARY KEY (id);
ALTER TABLE sc_mailinglist_internal_sub
ADD CONSTRAINT pk_mailinglist_internal_sub
PRIMARY KEY (id);

ALTER TABLE sc_mailinglist_external_user
ADD CONSTRAINT FK9290F7C94B1A1B47
FOREIGN KEY (listId)
REFERENCES sc_mailinglist_list (id);
ALTER TABLE sc_mailinglist_attachment
ADD CONSTRAINT FKCE814959DB1C14EE
FOREIGN KEY (messageId)
REFERENCES sc_mailinglist_message (id);
ALTER TABLE sc_mailinglist_internal_sub
ADD CONSTRAINT fk_subscriber_mailinglist_id
FOREIGN KEY (mailinglistid)
REFERENCES sc_mailinglist_list (id);
ALTER TABLE sc_mailinglist_message
ADD CONSTRAINT mailinglist_message_mailid_key
UNIQUE (mailId, componentId);
