ALTER TABLE SC_CRM_Contacts ADD 
	 CONSTRAINT PK_Crm_Contacts PRIMARY KEY   
	(
		id
	)   
;

ALTER TABLE SC_CRM_Delivery ADD 
	 CONSTRAINT PK_Crm_Delivery PRIMARY KEY   
	(
		id
	)   
;
ALTER TABLE SC_CRM_Events ADD 
	 CONSTRAINT PK_Crm_Events PRIMARY KEY   
	(
		id
	)   
;

ALTER TABLE SC_CRM_Infos ADD 
	 CONSTRAINT PK_Crm_Infos PRIMARY KEY   
	(
		id
	)   
;
ALTER TABLE SC_CRM_Participants ADD 
	 CONSTRAINT PK_Crm_Participants PRIMARY KEY   
	(
		id
	)   
;

ALTER TABLE SC_CRM_Contacts ADD CONSTRAINT FK_SC_CRM_Contacts_1 FOREIGN KEY (crmId) REFERENCES SC_CRM_Infos (id);
ALTER TABLE SC_CRM_Delivery ADD CONSTRAINT FK_SC_CRM_Delivery_1 FOREIGN KEY (crmId) REFERENCES SC_CRM_Infos (id);
ALTER TABLE SC_CRM_Delivery ADD CONSTRAINT FK_SC_CRM_Delivery_2 FOREIGN KEY (contactId) REFERENCES SC_CRM_Contacts (id);
ALTER TABLE SC_CRM_Events ADD CONSTRAINT FK_SC_CRM_Events_1 FOREIGN KEY (crmId) REFERENCES SC_CRM_Infos (id);
ALTER TABLE SC_CRM_Participants ADD CONSTRAINT FK_SC_CRM_Participants_1 FOREIGN KEY (crmId) REFERENCES SC_CRM_Infos (id);