Le publieur <b>$userName$</b>, vous demande de prendre connaissance de la réponse suivante :
<div style="background-color:#FFF9D7; border:1px solid #E2C822; padding:5px; width:390px;"><b>$ReplyDetail.title$</b>
$replyContent$
</div>

La question était :
<div style="background-color:#FFF9D7; border:1px solid #E2C822; padding:5px; width:390px;"><b>$QuestionDetail.title$</b>
$QuestionDetail.content$
</div>

