The publisher <b>$userName$</b> asks you to take note of the following answer:
<div style="background-color:#FFF9D7; border:1px solid #E2C822; padding:5px; width:390px;"><b>$ReplyDetail.title$</b>
$replyContent$
</div>

The question was:
<div style="background-color:#FFF9D7; border:1px solid #E2C822; padding:5px; width:390px;"><b>$QuestionDetail.title$</b>
$QuestionDetail.content$
</div>
