create table SC_SaasManager_Access (
  id int not null,
  uid varchar(100) not null,
  lastName varchar(100) not null,
  firstName varchar(100) not null,
  email varchar(100) not null,
  phone varchar(100) not null,
  company varchar(100),
  companyWebSite varchar(100),
  lang varchar(100),
  services varchar(1000),
  usersCount int,
  conditionsAgreement int not null,
  remarks varchar(1000),
  remoteAddress varchar(100) not null,
  requestDate date not null,
  achievementDate date,
  domainId varchar(100),
  userId varchar(100),
  userLogin varchar(100),
  userPassword varchar(100),
  spaceId varchar(100),
  componentIds varchar(1000),
  homeComponentId varchar(100),
  managementComponentId varchar(100)
);