DROP INDEX SC_FormsOnline_UserRights.IND_SC_FormsOnline_UserRights_1;
DROP INDEX SC_FormsOnline_UserRights.IND_SC_FormsOnline_UserRights_2;
DROP INDEX SC_FormsOnline_GroupRights.IND_SC_FormsOnline_GroupRights_1;   
DROP INDEX SC_FormsOnline_GroupRights.IND_SC_FormsOnline_GroupRights_2;   
